### ISSUE TITLE
GoogleCharts is undefined

### ISSUE THREAD

**Issue by clnt** [mmathias01/google-charts#13] opened 2018-07-12 16:28 UTC
Hi,

I am having some issues using this package in a Laravel application using Vue.js, using laravel-mix to handle Webpack.

As per the docs, I have added `import {GoogleCharts} from 'google-charts';` to my `app.js` file, webpack builds everything without errors.

I have a Vue component which calls `GoogleCharts.load(this.drawChart());` - this gives me `ReferenceError: GoogleCharts is not defined`

If I add `window.GoogleCharts = GoogleCharts;` to my `app.js` it will run the callback function `drawChart()` but then I get `ReferenceError: googleCharts is not defined` when it hits `let chart = new GoogleCharts.api.visualization.AreaChart(document.getElementById(this.chartDiv));`

I have attempted importing it into my `app.js` in different ways but none of them have been successful.

Any ideas?

**Comment by mmathias01** [comment] 2018-07-12 17:13
Hey!

This sounds a bit like a scoping issue - can you provide some code? Either a GIST or repo I can look at?

**Comment by clnt** [comment] 2018-07-12 18:03
Thanks for the speedy response :)

Unfortunately my repo is private but I have created Gist's of all the relevant stuff:

`app.js` https://gist.github.com/clnt/04017ddbeff518d276a2b251f49d1b5f

`MonitorView.vue` https://gist.github.com/clnt/1eaa933d5f0084250c787fadc0118745

`MonitorSelect.vue` https://gist.github.com/clnt/07e1c3d3a3cfee7a25855a6fa3c08e14

`Monitor.vue` (contains the GoogleChart stuff) https://gist.github.com/clnt/3b2c57acb3a4e3dbc6d9f5391ddd588e

If you need to see anything else let me know :)

Thanks!

**Comment by clnt** [comment] 2018-07-16 17:51
Hi mate,

I have managed to sort this now by using a vue-google-charts component, unfortunately I didn't get any further in figuring out why this would not work.

**Comment by mmathias01** [comment] 2018-07-16 21:21
@clnt Looks like you might have just needed to import {GoogleCharts} @ around line 8 of Monitor.vue, that or specifically reference window.GoogleCharts later on.

The problem is that in ES6 variables are module scoped and therefore importing something in app.js doesn't make it available to other modules  - even ones used by app.js.

**Comment by mmathias01** [comment] 2018-07-16 21:21
Let me know if you decide to try that, ill leave this issue open for now mostly for educational purposes :)

**Comment by clnt** [comment] 2018-07-17 00:06
@mmathias01 Oh cool thanks I didn't know that :) I gave it a go, it solved the initial undefined error which fixes the scoping issue but now I get `TypeError: __WEBPACK_IMPORTED_MODULE_1_google_charts__.a.api is undefined`

**Comment by mmathias01** [comment] 2018-07-19 18:32
I want to get to the bottom of this for sure especially since I originally wrote this for use with Vue.js and it works great LOL. Can you get me another gist? just of that file this time :) - also just to be sure - what file is WP throwing that error on? @clnt

**Comment by clnt** [comment] 2018-07-24 14:11
@mmathias01 When I get some spare time this week I will try and re-create the issue in a demo project :)

**Comment by clnt** [comment] 2018-08-09 00:48
@mmathias01 I have managed to reproduce the error in a new laravel installation, here it is: https://github.com/clnt/google-charts-issue-13

**Comment by TAUFEEQ1** [comment] 2018-09-19 13:43
i have the same issue here, was a solution reached?

**Comment by mmathias01** [comment] 2018-09-19 17:51
Here are a couple of gists that will hopefully help. These are from a working implementation that I actually used to develop the library.

1) [Generic Chart](https://gist.github.com/mmathias01/c699c38dad3263b36244c3c70d99eff8) - I used this as a generic chart base so that I could have multiple types of chart and not repeat any code

2) [Bar Chart](https://gist.github.com/mmathias01/c699c38dad3263b36244c3c70d99eff8) - This is an example of a chart that uses Generic Chart as a mixin so that it can use all the generic chart functionality without having to re-write it. 

Hopefully between these two things it will solve one or both of your issues. Let me know if it does not and I can dig in a bit more!

Thanks

**Comment by TAUFEEQ1** [comment] 2018-09-20 05:45
i have managed to make it work using the following:
In the entry js file(app.js), add;
//
import { GoogleCharts } from 'google-charts'
Vue.prototype.$GoogleCharts = GoogleCharts;
//
to avoid any trouble with 'this', define all functions as methods of the component for example,
use:
methods:{
drawChart(){
 this.$GoogleCharts; ///ok
},
}
instead of;
methods:{
compute_chart(){
 function drawChart(){
     this.$GoogleCharts; ///will cause errors
}
}
}
use this.$GoogleCharts.api.visualization instead of this.$GoogleCharts.visualization

**Comment by mmathias01** [comment] 2019-01-11 05:36
looks like this issue has been resolved. closing for now

**Closed by mmathias01** 2019-01-11 05:36 UTC
